Repository shankarlohar/Hacktober-Fests, pull requests merged in 2022-10, with the labels that each got.

#4 readme tutorial update
  README.md
Labels: hacktoberfest-accepted

#5 webpage tutorial update
  README.md
  index.html
Labels: hacktoberfest-accepted

#6 Update README.md
  README.md
Labels: hacktoberfest-accepted

#7 Update README.md
  README.md
Labels: hacktoberfest-accepted

#13 add card
  index.html
  style.css
Labels: hacktoberfest-accepted

#15 add contributor
  README.md
Labels: hacktoberfest-accepted

#17 change background-color
  style.css
Labels: hacktoberfest-accepted

#16 Added My name card in index.html
  index.html
  style.css
Labels: hacktoberfest-accepted

#18 Changes Made
  README.md
  index.html
  style.css
Labels: hacktoberfest-accepted

#29 add my card
  index.html
Labels: hacktoberfest-accepted

#33 first
  index.html
Labels: hacktoberfest-accepted

#34 Added my card Name in index.html
  index.html
  style.css
Labels: hacktoberfest-accepted

#36 second
  index.html
  style.css
Labels: hacktoberfest-accepted

#37 Added a new card
  index.html
Labels: hacktoberfest-accepted

#38 first
  index.html
Labels: hacktoberfest-accepted

#39 One
  index.html
Labels: hacktoberfest-accepted

#40 second
  style.css
Labels: hacktoberfest-accepted

#41 Added name card
  index.html
  style.css
Labels: hacktoberfest-accepted

#42 updated bg color
  style.css
Labels: hacktoberfest-accepted

#43 Updated index.html
  index.html
Labels: hacktoberfest-accepted

#44 fourth
  index.html
Labels: hacktoberfest-accepted

#45 I have updated the style sheet to make it more attractive .
  style.css
Labels: hacktoberfest-accepted

#46 I have updated the index.html file please merge my request
  index.html
Labels: hacktoberfest-accepted

#48 login page
  login page/lp.css
  login page/lp.html
Labels: hacktoberfest-accepted

#52 feat: my card
  index.html
Labels: hacktoberfest-accepted

#53 Change to green
  index.html
  style.css
Labels: hacktoberfest-accepted

#54 Login button Added
  index.html
  style.css
Labels: hacktoberfest-accepted

#56 modified index.html
  index.html
Labels: hacktoberfest-accepted

#58 #55 Fixed 405
  index.html
  lp.css
  lp.html
Labels: hacktoberfest-accepted

#59 added
  index.html
Labels: hacktoberfest-accepted

#60 Added by Shubhi
  index.html
Labels: hacktoberfest-accepted

#61 moved text Learning git and Github
  index.html
  style.css
Labels: hacktoberfest-accepted

#63 Background color Updated
  style.css
Labels: hacktoberfest-accepted

#62 Name card added
  index.html
Labels: hacktoberfest-accepted

#66 Add Joseph Jaison to the list
  index.html
  style.css
Labels: hacktoberfest-accepted

#68 changed README.md
  README.md
  index.html
Labels: hacktoberfest-accepted

#72 Made 'Login' button's position relative
  index.html
Labels: bug, hacktoberfest-accepted

#71 Fixed the Grid & Added a member
  README.md
  index.html
Labels: hacktoberfest-accepted

#74 add card
  index.html
Labels: hacktoberfest-accepted

#78 Fixed Navbar Color, Background color : Added another section
  README.md
  index.html
  style.css
Labels: hacktoberfest-accepted

#79 card added
  index.html
Labels: hacktoberfest-accepted

#80 added card and contributor
  README.md
  index.html
Labels: hacktoberfest-accepted

#81 added aman rana's profile card
  index.html
Labels: hacktoberfest-accepted

#82 card added
  index.html
Labels: hacktoberfest-accepted

#84 Itsimmad
  README.md
  index.html
  style.css
Labels: hacktoberfest-accepted

#85 Abhishek added Card
  README.md
  index.html
Labels: hacktoberfest-accepted

#86 Update style.css to make website responsive for the phone please merge it for my pp .
  style.css
Labels: hacktoberfest-accepted

#89 Added gradient background to profile cards.
  style.css
Labels: hacktoberfest-accepted

#91 Main
  index.html
Labels: hacktoberfest-accepted

#95 Changes to be committed:
  index.html
Labels: hacktoberfest-accepted

#96 beautified the website's scrollbar
  style.css
Labels: enhancement, hacktoberfest-accepted, css-kings

#97 background changed
  style.css
Labels: hacktoberfest-accepted

#98 navbar color changed
  index.html
Labels: hacktoberfest-accepted

#99 Profile added to Readme
  README.md
Labels: hacktoberfest-accepted

#100 updated body background.
  style.css
Labels: hacktoberfest-accepted

#102 updated index.html, style.css and README.md
  README.md
  index.html
  style.css
Labels: hacktoberfest-accepted

#106 Updated HTML Files
  index.html
Labels: hacktoberfest-accepted

#109 Updated CSS Files
  style.css
Labels: hacktoberfest-accepted

#110 Updated Navbar color
  index.html
Labels: hacktoberfest-accepted

#111 Updated Contributions List
  README.md
Labels: hacktoberfest-accepted

#112 Added card in index.html and updated readme.md
  README.md
  index.html
Labels: hacktoberfest-accepted

#113 Updated Initial Profile Card
  index.html
Labels: hacktoberfest-accepted

#114 Updated Styles CSS
  style.css
Labels: hacktoberfest-accepted

#115 Changed Navbar Color
  index.html
Labels: hacktoberfest-accepted

#116 Added My Contribution Profile
  README.md
Labels: hacktoberfest-accepted

#117 Responsive-Footer
  index.html
  style.css
Labels: hacktoberfest-accepted

#119 Responsive-Sticky-Header
  img/white.png
  index.html
  main.js
  style.css
Labels: hacktoberfest-accepted

#120 Update index.html
  README.md
  index.html
  style.css
Labels: hacktoberfest-accepted

#121 Update index.html
  index.html
Labels: hacktoberfest-accepted

#122 corrected navbar color
  style.css
Labels: hacktoberfest-accepted

#123 Added Font Families
  style.css
Labels: hacktoberfest-accepted

#124 updated hover effect on cards
  style.css
Labels: hacktoberfest-accepted

#125 Added About Us page to your website
  about.css
  aboutus.html
  img/135871289-photo-of-attractive-guy-celebrating-ecstatic-emotions-win-lottery-money-prize-yelling-loud-rejoicing.webp
  img/2672335.jpg
  img/excited-handsome-man-triumphing-raising-hands-up-shouting-joy-celebrating-victory-standing-against-blue-background_1258-66579 (1).webp
  img/excited-handsome-man-triumphing-raising-hands-up-shouting-joy-celebrating-victory-standing-against-blue-background_1258-66579.webp
  img/person.jpg
  index.html
Labels: hacktoberfest-accepted

#126 added my profile card
  index.html
Labels: hacktoberfest-accepted

#127 Added my profile card
  index.html
Labels: hacktoberfest-accepted

#128 prettifies the Navbar
  index.html
Labels: hacktoberfest-accepted

#131 Update README.md
  README.md
Labels: hacktoberfest-accepted

#130 Update index.html
  index.html
Labels: hacktoberfest-accepted

#118 added the story card to index.html and updated README.md
  README.md
  index.html
Labels: hacktoberfest-accepted

#132 Changed Header color which matches the background
  index.html
Labels: hacktoberfest-accepted

#134 Add Card
  index.html
Labels: hacktoberfest-accepted

#137 updated scrollbar opacity
  style.css
Labels: hacktoberfest-accepted

#138 Patch 1
  index.html
  style.css
Labels: hacktoberfest-accepted

#143 Added Umang profile card
  index.html
Labels: hacktoberfest-accepted

#144 new addition
  README.md
  index.html
  style.css
Labels: hacktoberfest-accepted

#145 fixed css
  index.html
  style.css
Labels: hacktoberfest-accepted

#148 updated scrollbar color
  style.css
Labels: hacktoberfest-accepted

#154 Editted cards UI
  .vscode/settings.json
  index.html
  main.js
  style.css
Labels: hacktoberfest-accepted

#157 Update style.css and make the cards more attractive kindly merge it fast so that it can be counted in my pr .
  style.css
Labels: hacktoberfest-accepted

#159 add a team member to the list
  README.md
  index.html
  style.css
Labels: hacktoberfest-accepted

#161 Ekraj Ghimire
  README.md
  index.html
  style.css
Labels: hacktoberfest-accepted

#163 Update index.html
  index.html
Labels: hacktoberfest-accepted

#165 Login page
  img/log.svg
  img/register.svg
  index.html
  lp.css
  lp.html
  main.js
  style.css
Labels: hacktoberfest-accepted

#167 changed colors
  style.css
Labels: hacktoberfest-accepted

#169 Changed background colors
  style.css
Labels: hacktoberfest-accepted

#162 Raj Kasaudhan
  README.md
  index.html
  style.css
Labels: hacktoberfest-accepted

#170 Prajwol Gautam
  README.md
  index.html
  style.css
Labels: hacktoberfest-accepted

#168 chnged opacity
  style.css
Labels: hacktoberfest-accepted

#171 added color
  style.css
Labels: hacktoberfest-accepted

#166 added profile card
  index.html
Labels: hacktoberfest-accepted

#173 added new card
  index.html
Labels: hacktoberfest-accepted

#174 Update index.html
  README.md
  style.css
Labels: hacktoberfest-accepted

#175 Update README.md
  README.md
Labels: hacktoberfest-accepted

#176 Update style.css
  style.css
Labels: hacktoberfest-accepted

#177 Added my card
  index.html
Labels: hacktoberfest-accepted

#179 modified-colors
  index.html
Labels: hacktoberfest-accepted
